# .github/workflows/templates/drift-detection.yml
name: Infrastructure Drift Detection

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  drift-detection:
    name: Detect Infrastructure Drift
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan for Drift
        run: terraform plan -detailed-exitcode -out=drift.plan

      - name: Check for Drift
        if: ${{ failure() }}
        run: |
          echo "Infrastructure drift detected! Please review the Terraform plan."
          exit 1

      - name: Upload Drift Plan
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: drift-plan
          path: drift.plan
