# .github/workflows/templates/policy-enforcement.yml
name: Policy Enforcement

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  enforce-policies:
    name: Enforce Policies with OPA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.0

      - name: Install OPA
        run: |
          wget https://github.com/open-policy-agent/opa/releases/download/v0.37.0/opa_linux_amd64
          chmod +x opa_linux_amd64
          sudo mv opa_linux_amd64 /usr/local/bin/opa

      - name: Download Policy Files
        run: |
          mkdir -p policies
          cp -R policies/ /policies/

      - name: Run OPA Tests
        run: |
          opa eval --format=pretty "data.terraform.security" -d policies/

      - name: Validate Against Policies
        run: |
          terraform validate -json | opa eval --input - --data policies/ 'data.terraform.security.allow'

      - name: Fail if Policies Violated
        if: failure()
        run: exit 1
