# .github/workflows/terraform-tests.yml
name: Terraform Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terratest:
    name: Run Terratest for ${{ github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false  # Disable Terraform wrapper for compatibility with Terratest

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Initialize Go Module
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          MODULE_PATH="./tests"
          mkdir -p $MODULE_PATH
          cd $MODULE_PATH
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ github.repository_owner }}/$REPO_NAME
          fi
          go mod tidy

      - name: Install Terratest Dependencies
        run: |
          cd ./tests
          go get github.com/gruntwork-io/terratest/modules/terraform

      - name: Run Terratest
        run: |
          cd ./tests
          go test -v -timeout 30m ./...

  unit-tests:
    name: Run Terraform Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false  # Disable Terraform wrapper for compatibility with Terratest

      - name: Install Required Packages
        run: |
          sudo apt-get update && sudo apt-get install -y curl wget unzip python3-pip

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Initialize Go Module for Unit Tests
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          MODULE_PATH="./tests/unit"
          mkdir -p $MODULE_PATH
          cd $MODULE_PATH
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ github.repository_owner }}/$REPO_NAME
          fi
          go mod tidy

      - name: Install Unit Test Dependencies
        run: |
          cd ./tests/unit
          go get github.com/gruntwork-io/terratest/modules/terraform

      - name: Run Unit Tests
        run: |
          cd ./tests/unit
          go test -v -timeout 30m ./...
