name: Sync Shared Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Sync Shared Files
        id: sync
        uses: varunsridharan/action-github-workflow-sync@3.4
        with:
          GITHUB_TOKEN: ${{ secrets.CEYX_SHARED_TOKEN }}
          REPOSITORIES: |
            HalcyonOps/Ceyx-AWS-EC2
            HalcyonOps/Ceyx-AWS-VPC
          WORKFLOW_FILES: |
            resources/shared/CODE_OF_CONDUCT.md=../../CODE_OF_CONDUCT.md
            resources/shared/CONTRIBUTING.md=../../CONTRIBUTING.md
            resources/shared/LICENSE=../../LICENSE
            resources/shared/SECURITY.md=../../SECURITY.md
          WORKFLOW_FILES_DIR: .
          PULL_REQUEST: true
          COMMIT_MESSAGE: "Sync shared files from source repository"

      - name: Enable Auto-Merge for PRs
        run: |
          repos=("HalcyonOps/Ceyx-AWS-EC2" "HalcyonOps/Ceyx-AWS-VPC")
          for repo in "${repos[@]}"; do
            pr_url=$(gh pr list --repo "$repo" --author "R055LE" --state open --json url --jq '.[0].url')
            if [ -n "$pr_url" ]; then
              gh pr merge --auto --squash "$pr_url" --repo "$repo"
            else
              echo "No open pull request found for $repo"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.CEYX_SHARED_TOKEN }}
