# Add these permissions at the top of your workflow file
permissions:
  contents: write
  pull-requests: write
  actions: write

name: Sync Resources

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_SHARED }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Fetch from Source
        run: |
          git remote add source git@github.com:HalcyonOps/Ceyx-Shared.git
          git fetch source

      - name: Sync Resources
        run: |
          git checkout -b sync/resources
          
          # First copy resources directory with nested items
          git checkout source/main -- resources/
          
          # Then copy contents to root while preserving nested structure
          cp -r resources/* .
          rm -rf resources/
          
          # Commit if there are changes
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: sync resources from shared repo"
            git push origin sync/resources --force
          fi

      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "sync/resources"
          destination_branch: "main"
          pr_title: "chore: sync resources from shared repo"
          pr_body: "Automated PR to sync resources from shared repository."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automerge"

      - name: Auto-merge Pull Request
        if: steps.create-pr.outputs.pr_number
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ steps.create-pr.outputs.pr_number }}
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"