name: Sync Shared Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Sync Shared Files
        id: sync
        uses: varunsridharan/action-github-workflow-sync@3.4
        with:
          GITHUB_TOKEN: ${{ secrets.CEYX_SHARED_TOKEN }}
          REPOSITORIES: |
            HalcyonOps/Ceyx-AWS-EC2
            HalcyonOps/Ceyx-AWS-VPC
          WORKFLOW_FILES: |
            resources/shared/CODE_OF_CONDUCT.md=../../CODE_OF_CONDUCT.md
            resources/shared/CONTRIBUTING.md=../../CONTRIBUTING.md
            resources/shared/LICENSE=../../LICENSE
            resources/shared/SECURITY.md=../../SECURITY.md
            resources/workflows/security-scan.yml=security-scan.yml
            resources/workflows/terraform-ci.yml=terraform-ci.yml
            resources/workflows/terraform-tests.yml=terraform-tests.yml
          WORKFLOW_FILES_DIR: .
          PULL_REQUEST: true
          COMMIT_MESSAGE: "Sync shared files from source repository"

      - name: Enable Auto-Merge for PRs
        run: |
          repos=("HalcyonOps/Ceyx-AWS-EC2" "HalcyonOps/Ceyx-AWS-VPC")
          for repo in "${repos[@]}"; do
            pr_number=$(gh pr list --repo "$repo" --author "R055LE" --state open --json number --jq '.[0].number')
            if [ -n "$pr_number" ]; then
              # Enable auto-merge for the PR
              gh pr merge --auto --squash "$pr_number" --repo "$repo"
              # Wait for the PR to be merged
              while [ "$(gh pr view "$pr_number" --repo "$repo" --json state --jq '.state')" != "MERGED" ]; do
                echo "Waiting for PR #$pr_number to merge..."
                sleep 5
              done
              # Retrieve the branch name associated with the PR
              branch_name=$(gh pr view "$pr_number" --repo "$repo" --json headRefName --jq '.headRefName')
              # Delete the branch after merging
              gh api -X DELETE "repos/$repo/git/refs/heads/$branch_name"
            else
              echo "No open pull request found for $repo"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.CEYX_SHARED_TOKEN }}
