name: Sync Resources
on:
  push:
    paths:
      - 'resources/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync.yml
          COMMIT_BODY: "chore: sync shared resources"
          PR_BODY: |
            Automated PR to sync shared resources from the central repository.
            
            Please review the changes before merging.
