name: Sync Shared Resources

on:
  push:
    paths:
      - 'resources/**'
      - 'repositories.yml'
  workflow_dispatch:

jobs:
  sync-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Central Repository
        uses: actions/checkout@v4.2.2
        
      - name: Setup Environment
        uses: actions/setup-node@v4.1.0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

          # Install yq
          YQ_VERSION=v4.34.1
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Verify yq Installation
        run: yq --version

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1.11.0
        with:
          app-id: ${{ secrets.CEYX_SHARED_RESOURCES_SYNC_APP_ID }}
          private-key: ${{ secrets.CEYX_SHARED_RESOURCES_SYNC_APP_PRIVATE_KEY }}

      - name: Read Target Repositories
        id: get_repos
        run: |
          REPOS=$(yq '.repositories | map(.name + " " + .owner + " " + .path) | join(",")' repositories.yml)
          echo "REPOS=${REPOS}" >> $GITHUB_OUTPUT
        env:
          REPOS_FILE: repositories.yml

      - name: Validate repositories.yml
        run: |
          yq e '.' repositories.yml > /dev/null
        shell: bash

      - name: Sync to Target Repositories
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPOS: ${{ steps.get_repos.outputs.REPOS }}
        run: |
          if [ -z "$REPOS" ]; then
            echo "No repositories found to sync."
            exit 0
          fi

          IFS=',' read -ra REPO_ARRAY <<< "$REPOS"
          for repo in "${REPO_ARRAY[@]}"; do
            IFS=' ' read -ra INFO <<< "$repo"
            REPO_NAME=${INFO[0]}
            REPO_OWNER=${INFO[1]}
            RESOURCE_PATH=${INFO[2]}

            echo "Syncing to $REPO_OWNER/$REPO_NAME"

            # Clone the target repository using the GitHub App token
            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO_OWNER}/${REPO_NAME}.git temp_repo || { 
              echo "Failed to clone repository $REPO_OWNER/$REPO_NAME"; 
              exit 1; 
            }
            cd temp_repo

            # Ensure we're on the main branch
            git checkout main || { 
              echo "Failed to checkout main branch in $REPO_OWNER/$REPO_NAME"; 
              exit 1; 
            }

            # Copy updated resources to the target repository
            cp -R ../resources/* ./ || { 
              echo "Failed to copy resources to $REPO_OWNER/$REPO_NAME"; 
              exit 1; 
            }

            # Stage all changes, including new files
            git add .

            # Check if there are any changes to commit
            if git diff --cached --quiet; then
              echo "No changes detected in $REPO_OWNER/$REPO_NAME. Skipping commit."
            else
              # Configure Git
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

              # Commit changes
              git commit -m "chore: update shared resources from central repository" || { 
                echo "Failed to commit changes in $REPO_OWNER/$REPO_NAME"; 
                exit 1; 
              }

              # Push changes
              git push origin main || { 
                echo "Git push failed for repository $REPO_OWNER/$REPO_NAME"; 
                exit 1; 
              }
              echo "Successfully synced $REPO_OWNER/$REPO_NAME."
            fi

            cd ..
            rm -rf temp_repo
          done
        shell: /usr/bin/bash -e {0}

